### ISSUE TITLE
Filtering including sub-calls

### ISSUE THREAD

**Issue by Arkoniak** [DevJac/OwnTime.jl#3]
It would be nice to have option to filter not only exact stackframes, but also all inner calls as well (sorry, may be these are wrong words, I hope example will explain it better).

From README example
```
julia> totaltime(stackframe_filter=filecontains("mycode.jl"))
 [1]  72% => myfunc() at mycode.jl:2
 [2]  14% => myfunc() at mycode.jl:3
```
In my workflow next step would be to go into  `[1]  72% => myfunc() at mycode.jl:2` May be something like 
```
julia> totaltime(stackframe_filter=stackframe -> stackframe.func == :myfunc[2], all = true)
 [1]  72% => myfunc() at mycode.jl:2
 [2]  72% => rand at Random.jl:277 [inlined]
 [3]  63% => rand(::Type{Float64}, ::Tuple{Int64,Int64,Int64}) at gcutils.jl:91
...
```
In perfect word it could be interesting to also having something like this
```
julia> totaltime(stackframe_filter=stackframe -> stackframe.func == :myfunc[2], all = true, relative = true)
 [1]  100% => myfunc() at mycode.jl:2
 [2]  100% => rand at Random.jl:277 [inlined]
 [3]  88% => rand(::Type{Float64}, ::Tuple{Int64,Int64,Int64}) at gcutils.jl:91
...
```

**Comment by DevJac** [comment]
If I understand you correctly, you want to be able to "drill down" to see how time is being spent on specific lines?

You could use the tree view given by the Profile package in the standard library, or you could use one of the tree visualization tools, like https://github.com/timholy/ProfileView.jl. I wish there was a terminal interface to drill down into the tree view given by Profile.

Or, you could look at the output from `OwnTime.stacktrace()` and filter that to include only those stackframes you are interested in, and then pass the stacktraces to `owntime` or `totaltime`. Something like:

```julia
sts = OwnTime.stacktraces()
filtered_sts = my_filter(sts)
owntime(filtered_sts)
```
or
```julia
owntime(my_filter(OwnTime.stacktraces()))
```

As in https://github.com/JuliaLang/julia/blob/master/base/stacktraces.jl#L74: A StackTrace is just a Vector of StackFrames.

In `my_filter` you'd want to filter out all stacktraces that do not include `myfunc` line 2, and you'd want to trim the stacktraces that do contain that line. Deeper stackframes appear first in the stacktraces.

Later today I will try coding this and maybe add it to the library if it's general enough.

**Comment by DevJac** [comment]
This is pretty close to your perfect world: :wink:

```julia
julia> function stackdepth(root_stackframe_filter, depth)
           function (stacktrace)
               for i in length(stacktrace):-1:1
                   if root_stackframe_filter(stacktrace[i])
                       return stacktrace[max(1, i-depth):i]
                   end
               end
               StackTraces.StackFrame[]
           end
       end
stackdepth (generic function with 1 method)

julia> sts = OwnTime.stacktraces();

julia> totaltime(filter(!isempty, stackdepth(sf -> sf.func == :myfunc && sf.line == 2, 0).(sts)))
 [1] 100% => myfunc() at mycode.jl:2


julia> totaltime(filter(!isempty, stackdepth(sf -> sf.func == :myfunc && sf.line == 2, 1).(sts)))
 [1] 100% => rand at Random.jl:277 [inlined]
 [2] 100% => myfunc() at mycode.jl:2


julia> totaltime(filter(!isempty, stackdepth(sf -> sf.func == :myfunc && sf.line == 2, 2).(sts)))
 [1] 100% => rand at Random.jl:277 [inlined]
 [2] 100% => myfunc() at mycode.jl:2
 [3]  96% => rand(::Type{Float64}, ::Tuple{Int64,Int64,Int64}) at gcutils.jl:91
 [4]   4% => rand(::Type{Float64}, ::Tuple{Int64,Int64,Int64}) at Random.jl:289

julia> totaltime( stackdepth(sf -> sf.func == :myfunc && sf.line == 2, 2).(sts) )
 [1]  89% => rand at Random.jl:277 [inlined]
 [2]  89% => myfunc() at mycode.jl:2
 [3]  50% => rand(::Type{Float64}, ::Tuple{Int64,Int64,Int64}) at gcutils.jl:91
 [4]  39% => rand(::Type{Float64}, ::Tuple{Int64,Int64,Int64}) at Random.jl:289

```

I think the best solution for what you're tying to do would be a terminal interface that makes exploring the Profile tree view more manageable. I don't think that exists yet, and I'm not sure if I want to include that in this library.

But, as you can see from `OwnTime.stacktraces()`, Julia makes it fairly easy to get the sampled StackTraces (remember, a StackTrace is a Vector of StackFrames) from its sampling profiler. Once you have those you can analyse them in endless ways.

**Comment by Arkoniak** [comment]
Thank you! That will be very useful!
